version: 1.0.{build}

configuration: Release

platform: Any CPU

pull_requests:
  do_not_increment_build_number: true
  
image: Visual Studio 2017

before_build:
- nuget restore

build_script:
 - dotnet restore Amplified.CSharp
 - dotnet build Amplified.CSharp

test_script:
 - dotnet restore Amplified.CSharp.Tests
 - dotnet build Amplified.CSharp.Tests
 - dotnet test Amplified.CSharp.Tests/Amplified.CSharp.Tests.csproj

nuget:
  project_feed: true
  
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal