version: 1.0.{build}

configuration: Release

platform: Any CPU

pull_requests:
  do_not_increment_build_number: true
  
image: Visual Studio 2017

before_build:
- nuget restore

build_script:
 - dotnet restore Amplified.CSharp
 - dotnet build Amplified.CSharp

test_script:
 - dotnet restore Amplified.CSharp.sln
 - dotnet restore Amplified.CSharp.Tests
 - dotnet build Amplified.CSharp.Tests
 - dotnet test Amplified.CSharp.Tests/Amplified.CSharp.Tests.csproj
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"Amplified.CSharp.Tests.dll -noshadow" -filter:"+[Amplified.CSharp]*  -[Amplified.CSharp]Amplified.CSharp.Properties.*" -excludebyattribute:*.ExcludeFromCoverage* -hideskipped:All -output:coverage.xml

after_test:
 - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
 - pip install codecov
 - codecov -f "coverage.xml" -t 75b80682-b7f7-47c4-b31a-925e59331076

nuget:
  project_feed: true
  
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal